// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB953bZgtARU3FzmF_wlVHkEGvagV1sT_g',
    appId: '1:942734904837:web:c87494c388003964d1166c',
    messagingSenderId: '942734904837',
    projectId: 'firestore-database-crud-simple',
    authDomain: 'firestore-database-crud-simple.firebaseapp.com',
    storageBucket: 'firestore-database-crud-simple.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1vbACNXh1gPAmOIZXQurH-vXVtOLda_Y',
    appId: '1:942734904837:android:ab96bbedbd56a52ad1166c',
    messagingSenderId: '942734904837',
    projectId: 'firestore-database-crud-simple',
    storageBucket: 'firestore-database-crud-simple.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJqW3VelgDSeciaGOhLkenqFMwSfnhLqk',
    appId: '1:942734904837:ios:3c48d764327ff412d1166c',
    messagingSenderId: '942734904837',
    projectId: 'firestore-database-crud-simple',
    storageBucket: 'firestore-database-crud-simple.appspot.com',
    iosClientId: '942734904837-n435i14beh1omhpstsj7a496ip0j08a7.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreDatabaseCrudExample2022',
  );
}
